name: Pull Request Info

on:
  pull_request:

jobs:
  TareaPR:
    runs-on: ubuntu-22.04

    steps:
      - name: Mostrar datos del Pull Request
        run: |
          echo "===== DATOS DEL PULL REQUEST ====="
          echo "Rama destino: ${{ github.event.pull_request.base.ref }}"
          echo "Rama origen: ${{ github.event.pull_request.head.ref }}"
          echo "Título: ${{ github.event.pull_request.title }}"
          echo "Contenido: ${{ github.event.pull_request.body }}"
          echo "Estado: ${{ github.event.pull_request.state }}"
          echo "Fusionado: ${{ github.event.pull_request.merged }}"
